# Site settings
name: name
email: email
url: url
description: "毕业于HDU，记录日常工作中的学习总结。目前是某甲方的安全工程师"
author: "Halo"
title: "Halo’s Blog"
permalink: pretty
baseurl: /

# social
github:
  username: Ns1ookup

twitter:
  username: Ns1ookup